$lines = @(
''import ''../services/bittensor_service.dart'';'',
''import ''package:flutter_riverpod/flutter_riverpod.dart'';'',
''import ''../services/supabase_service.dart'';'',
'''',
''final portfolioProvider = FutureProvider.family<Map<String, dynamic>?, String>((ref, userId) async {'',
''  // For Marcus user, enrich with coldkey data'',
''  // Depend on coldkey refresh so invalidating it forces fresh data (use .future for value + propagation)'',
''  final coldkeyData = await ref.watch(coldkeyRefreshProvider.future);'',
'''',
''  if (userId.contains(''marcus'') || userId == ''marcus-demo-1'') {'',
''    ref.read(coldkeyLastSyncProvider.notifier).state = DateTime.now();'',
''    final base = await SupabaseService.getUserPortfolio(userId) ?? {}; '',
'''',
''    // Merge: use coldkey totals as primary, keep other assets'',
''    return {'',
''      ...base,'',
''      ''total_value'': coldkeyData[''estimated_value_usd''],'',
''      ''bittensor_coldkey'': coldkeyData[''coldkey''],'',
''      ''tao_staked'': coldkeyData[''tao_staked''],'',
''      ''current_price'': coldkeyData[''current_price''],'',
''      ''monthly_change'': coldkeyData[''monthly_change''],'',
''      ''last_updated'': coldkeyData[''last_updated''],'',
''      ''is_coldkey_live'': coldkeyData[''is_live''],'',
''      ''assets'': coldkeyData[''assets''] ?? base[''assets''],'',
''    };'',
''  }'',
''  return SupabaseService.getUserPortfolio(userId);'',
''});'',
'''',
''final coldkeyRefreshProvider = FutureProvider<Map<String, dynamic>>((ref) async {'',
''  return BittensorService.refreshColdkeyData();'',
''});'',
'''',
''final coldkeyLastSyncProvider = StateProvider<DateTime?>((ref) => null);'',
'')'
$content = $lines -join "n"
Set-Content -LiteralPath 'C:\Users\Marcus\float_financial\lib\shared\providers\portfolio_provider.dart' -Value $content -NoNewline
Write-Output "portfolio_provider.dart restored + propagation fix applied"
Get-Content -LiteralPath 'C:\Users\Marcus\float_financial\lib\shared\providers\portfolio_provider.dart' -Raw
