import '../models/subnet_position.dart';

/// Severity levels for yield alerts.
enum AlertSeverity { low, medium, high }

/// A single alert generated by [YieldAlertEngine].
class YieldAlert {
  final int subnetId;
  final String type; // 'apy_drop', 'apy_spike', 'alpha_price_drop', 'alpha_price_spike'
  final String message;
  final AlertSeverity severity;
  final DateTime timestamp;

  const YieldAlert({
    required this.subnetId,
    required this.type,
    required this.message,
    required this.severity,
    required this.timestamp,
  });
}

/// Monitors subnet APY and alpha-price changes between two snapshots.
class YieldAlertEngine {
  static const double apyThresholdPct = 2.0;
  static const double priceThresholdPct = 5.0;

  /// Compares [current] against [previous] positions and returns alerts.
  List<YieldAlert> checkAlerts(
    List<SubnetPosition> current,
    List<SubnetPosition> previous,
  ) {
    final prevById = {for (final p in previous) p.subnetId: p};
    final alerts = <YieldAlert>[];
    final now = DateTime.now();

    for (final cur in current) {
      final prev = prevById[cur.subnetId];
      if (prev == null) continue;

      final apyDelta = cur.apy - prev.apy;
      if (apyDelta.abs() > apyThresholdPct) {
        final isDrop = apyDelta < 0;
        alerts.add(YieldAlert(
          subnetId: cur.subnetId,
          type: isDrop ? 'apy_drop' : 'apy_spike',
          message:
              'Subnet ${cur.subnetId} APY ${isDrop ? 'fell' : 'rose'} ${apyDelta.abs().toStringAsFixed(2)}% '
              '(${prev.apy.toStringAsFixed(2)}% → ${cur.apy.toStringAsFixed(2)}%)',
          severity: _severity(apyDelta.abs(), [3.0, 5.0]),
          timestamp: now,
        ));
      }

      if (prev.alphaPriceTao > 0) {
        final priceDeltaPct =
            (cur.alphaPriceTao - prev.alphaPriceTao) / prev.alphaPriceTao * 100;
        if (priceDeltaPct.abs() > priceThresholdPct) {
          final isDrop = priceDeltaPct < 0;
          alerts.add(YieldAlert(
            subnetId: cur.subnetId,
            type: isDrop ? 'alpha_price_drop' : 'alpha_price_spike',
            message:
                'Subnet ${cur.subnetId} alpha price ${isDrop ? 'fell' : 'rose'} ${priceDeltaPct.abs().toStringAsFixed(1)}% '
                '(${prev.alphaPriceTao.toStringAsFixed(4)} → ${cur.alphaPriceTao.toStringAsFixed(4)})',
            severity: _severity(priceDeltaPct.abs(), [8.0, 15.0]),
            timestamp: now,
          ));
        }
      }
    }
    return alerts;
  }

  AlertSeverity _severity(double magnitude, List<double> bands) {
    if (magnitude >= bands[1]) return AlertSeverity.high;
    if (magnitude >= bands[0]) return AlertSeverity.medium;
    return AlertSeverity.low;
  }
}
